# Generated by Django 4.1.1 on 2022-09-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=255)),
                ('manaCost', models.CharField(max_length=100)),
                ('cmc', models.IntegerField()),
                ('superType', models.CharField(max_length=100)),
                ('cardType', models.CharField(max_length=100)),
                ('cardSet', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Card_subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtype', to='card.card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='card.card')),
            ],
        ),
    ]
