# Generated by Django 4.1.1 on 2022-09-13 15:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_colour_card_subtype_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
        ),
        migrations.CreateModel(
            name='Card_supertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
        ),
        migrations.CreateModel(
            name='Card_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
        ),
        migrations.RenameField(
            model_name='card_colour',
            old_name='colour',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card_subtype',
            old_name='subtype',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cardType',
        ),
        migrations.RemoveField(
            model_name='card',
            name='superType',
        ),
        migrations.RemoveField(
            model_name='card_colour',
            name='card',
        ),
        migrations.RemoveField(
            model_name='card_subtype',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='colours',
            field=models.ManyToManyField(to='card.card_colour'),
        ),
        migrations.AddField(
            model_name='card',
            name='subtypes',
            field=models.ManyToManyField(to='card.card_subtype'),
        ),
        migrations.AddField(
            model_name='card_colour',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AddField(
            model_name='card_subtype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AddField(
            model_name='card',
            name='cardTypes',
            field=models.ManyToManyField(to='card.card_type'),
        ),
        migrations.AddField(
            model_name='card',
            name='superTypes',
            field=models.ManyToManyField(to='card.card_supertype'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card_set'),
        ),
    ]
